language: php
php:
 - 5.5
 - 5.6
 - hhvm

script: 
 # check php script syntax
 - bash .travis.phplint.sh

notification:
 irc:
  channels:
   - "irc.ozinger.org#libredev"
  on_success: change
  on_failure: always
  template:
    - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
 email:
  recipients:
   - revi@reviwiki.info
  on_success: change
  on_failure: always
